--- 
addons: 
  apt: 
    packages: ~
cache: cargo
language: rust
matrix: 
  allow_failures: 
    - 
      os: osx
os: 
  - linux
  - osx
rust: 
  - nightly
script: 
  - "rustup override set nightly"
  - "rustup target install wasm32-unknown-unknown"
  - "cargo web start --example basic --release"
sudo: false